# Generated by Django 5.0.7 on 2024-10-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryimg',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
