# Generated by Django 5.0.7 on 2024-10-09 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='userapp.user')),
            ],
        ),
    ]
