# Generated by Django 5.0.7 on 2024-09-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dataentry',
        ),
    ]
