# Generated by Django 5.0.7 on 2024-09-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='Email',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='Name',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
