# Generated by Django 5.0.7 on 2024-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0007_indexblog_remove_dataentry_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblog',
            name='Date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='indexblog',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
