# Generated by Django 5.0.7 on 2024-09-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0008_alter_indexblog_date_alter_indexblog_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indexblog',
        ),
    ]
