# Generated by Django 5.0.7 on 2024-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0011_userenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='image/')),
                ('Title', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=10)),
            ],
        ),
    ]
