# Generated by Django 5.0.7 on 2024-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0013_aboutdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdata',
            name='Position',
            field=models.CharField(max_length=50),
        ),
    ]
