# Generated by Django 5.0.7 on 2024-09-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0014_alter_aboutdata_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicesdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
    ]
