# Generated by Django 5.0.7 on 2024-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0016_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Quantity',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.IntegerField(max_length=200),
        ),
    ]
