# Generated by Django 5.0.7 on 2024-09-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0019_alter_cart_quantity_alter_cart_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
