# Generated by Django 5.0.7 on 2024-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0020_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='image/')),
                ('Product', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField(default=1)),
                ('Total', models.IntegerField(default=0)),
            ],
        ),
    ]
