# Generated by Django 5.0.7 on 2024-09-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0024_alter_cart_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
