# Generated by Django 5.0.7 on 2024-09-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0026_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.IntegerField(default=1),
        ),
    ]
