# Generated by Django 5.0.7 on 2024-09-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0027_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='Price',
            field=models.IntegerField(max_length=10),
        ),
    ]
