# Generated by Django 5.0.7 on 2024-09-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untreeapp', '0029_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
