# Generated by Django 5.0.7 on 2024-10-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authusermodel',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
