# Generated by Django 5.0.7 on 2024-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
