# Generated by Django 5.0.7 on 2024-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0002_superadmin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.FileField(upload_to='img/'),
        ),
    ]
