# Generated by Django 5.0.7 on 2024-11-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0007_alter_products_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
