# Generated by Django 5.0.7 on 2024-11-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0009_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
