# Generated by Django 5.0.7 on 2024-11-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0012_remove_products_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_Photo', models.ImageField(upload_to='image/')),
                ('cart_Product', models.CharField(max_length=20)),
                ('cart_Price', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
