# Generated by Django 5.0.7 on 2024-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
