# Generated by Django 5.0.7 on 2024-11-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0015_products_available_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
