# Generated by Django 5.0.7 on 2024-11-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0016_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_ids',
            field=models.TextField(),
        ),
    ]
