# Generated by Django 5.0.7 on 2024-11-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0017_alter_order_product_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
