# Generated by Django 5.0.7 on 2024-11-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0019_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='city',
        ),
    ]
