# Generated by Django 5.0.7 on 2024-11-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0020_rename_state_order_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartdata',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
