# Generated by Django 5.0.7 on 2024-11-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0022_cartdata_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartdata',
        ),
    ]
