# Generated by Django 5.0.7 on 2024-11-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0023_delete_cartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanelapp.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanelapp.users')),
            ],
        ),
    ]
