# Generated by Django 5.0.7 on 2024-11-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanelapp', '0024_cartdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('Contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanelapp.users')),
            ],
        ),
    ]
