# Generated by Django 5.0.7 on 2024-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indexentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('catagory', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
