# Generated by Django 5.0.7 on 2024-11-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indexentry',
        ),
    ]
