# Generated by Django 5.0.7 on 2024-11-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeapp', '0005_alter_login_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
