# Generated by Django 5.0.7 on 2024-11-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeapp', '0007_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
