# Generated by Django 5.0.7 on 2024-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumeapp', '0008_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
