# Generated by Django 5.0.7 on 2024-10-14 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catagoryapp', '0002_alter_category_categoryimg'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimage', models.ImageField(upload_to='image/')),
                ('blogtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catagoryapp.category')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='userapp.user')),
            ],
        ),
    ]
