# Generated by Django 5.0.7 on 2024-10-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data',
            new_name='date',
        ),
    ]
