# Generated by Django 5.0.7 on 2024-10-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_data_comment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
