# Generated by Django 5.0.7 on 2024-10-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_delete_comment'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('blogid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogusers', to='blogapp.blog')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='userapp.user')),
            ],
        ),
    ]
