# Generated by Django 5.0.7 on 2024-08-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=200)),
                ('Disctiption', models.CharField(max_length=200)),
                ('Readmore', models.CharField(max_length=200)),
                ('footer', models.CharField(max_length=200)),
            ],
        ),
    ]
