# Generated by Django 5.0.7 on 2024-08-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('ContactNo', models.IntegerField(max_length=12)),
                ('Gender', models.CharField(max_length=10)),
                ('Hobby', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
            ],
        ),
    ]
