# Generated by Django 5.0.7 on 2024-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanelapp', '0002_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Duration',
            field=models.CharField(max_length=50),
        ),
    ]
