# Generated by Django 5.0.7 on 2024-09-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanelapp', '0003_alter_admission_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
