# Generated by Django 5.0.7 on 2024-10-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanelapp', '0006_alter_admission_joindate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Number', models.IntegerField(max_length=20)),
                ('Pnumber', models.IntegerField(max_length=20)),
                ('Study', models.CharField(max_length=50)),
                ('Reference', models.CharField(max_length=50)),
                ('Inquiry', models.CharField(max_length=50)),
            ],
        ),
    ]
