# Generated by Django 5.0.7 on 2024-10-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanelapp', '0007_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
