# Generated by Django 5.0.7 on 2024-10-03 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanelapp', '0009_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
