# Generated by Django 5.0.7 on 2024-10-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanelapp', '0010_delete_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Study', models.CharField(max_length=50)),
                ('Reference', models.CharField(max_length=50)),
                ('Inquiry', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=20)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
