# Generated by Django 5.0.7 on 2024-10-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanelapp', '0013_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
