# Generated by Django 5.0.7 on 2024-10-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanelapp', '0015_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='expectedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='visitedDate',
            field=models.DateTimeField(),
        ),
    ]
