# Generated by Django 5.0.7 on 2024-08-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('maths', models.IntegerField(max_length=20)),
                ('sci', models.IntegerField(max_length=20)),
                ('phy', models.IntegerField(max_length=20)),
                ('total', models.IntegerField(max_length=20)),
                ('per', models.IntegerField(max_length=20)),
            ],
        ),
    ]
