# Generated by Django 5.0.7 on 2024-08-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='maths',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='per',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='phy',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='sci',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='total',
            field=models.CharField(max_length=20),
        ),
    ]
