# Generated by Django 5.0.7 on 2024-09-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessionapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
